version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.3.0
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build container
          command: docker build -t "anchore/anchore-engine:ci" .
      - anchore/analyze_local_image:
          image_name: example/test:latest
          timeout: '500'
          dockerfile_path: ./Dockerfile
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports