version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.3.0
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: 'docker.io/library/nginx:latest'
          timeout: '300'
          policy_failure: True
